return {
    TelescopePrompt = "",
    NvimTree = "",
    DiffviewFiles = "署",
    toggleterm = "",
    RunCode = "",
    treesitter = "",
    format = "",
    lsp = "",
    modified = "●",
    file = "",
    diagnostics = "■",
    spaces = "⇥",
    progress = { "__", "▁▁", "▂▂", "▃▃", "▄▄", "▅▅", "▆▆", "▇▇" },
    spinner = {
        "▏",
        "▎",
        "▍",
        "▌",
        "▋",
        "▊",
        "▉",
        "▊",
        "▋",
        "▌",
        "▍",
        "▎",
    }
}
